services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - WIDURI_DATABASE_NAME=${WIDURI_DATABASE_NAME}
      - WIDURI_DATABASE_USERNAME=${WIDURI_DATABASE_USERNAME}
      - WIDURI_DATABASE_PASSWORD=${WIDURI_DATABASE_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.4.6
    environment:
      - MYSQL_DATABASE=${WIDURI_DATABASE_NAME}
      - MYSQL_USER=${WIDURI_DATABASE_USERNAME}
      - MYSQL_PASSWORD=${WIDURI_DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql # Initializes the database on first run
      - db-data:/var/lib/mysql # Persists database data
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

volumes:
  db-data:
