spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: java
    password: java
    url: jdbc:mysql://localhost:3306/widuri_estore
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true