#spring:
#  config:
#    activate:
#      on-profile: dev
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: java
#    password: java
#    url: jdbc:mysql://localhost:3306/widuri_estore
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      minimum-idle: 10
#      maximum-pool-size: 20
#  jpa:
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
#
#application:
#  security:
#    # for development only
#    #    secret-key: 702b7afafca85bb203af3eb5d07b0c3a1ad9cee18a4ff72202b227fb989d06aea1ec1beffda5dd20360a05878f926a712a32af61a31559f20ffaf94fc58f77ba7d6d68af7f2fa8dbb0efef750b0b93b0a9e2728f3144fea133c937cb008f1710898dba68ea700e3659f67bc44514ed7f754ac882c20d8dd161de08628032a5a47180914dc9cb72b09f87b1487e415e5a620ac68b3e106befcb6eccf4361e9a29a00e39b536bb92b07f6d27eb6fbf47b5f5d8d3ab3d50d69f80511e958150aada138fa020ebd7df63c7462df31806a471005a715eb12261fbaa4cb02f3ad7d8aab6c59d707f68038cae081db9e15b261e75ca09a94cc7158486b46b06c168cff1
#    jwt-ttl: 9000000 # 50minutesS
#    secret-key: ${JWT_SECRET_KEY}

spring:
  # ===================================================================
  # DEFAULT CONFIGURATION (active when no profile is set), for local development.
  # ===================================================================
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
    username: ${WIDURI_DATABASE_USERNAME}
    password: ${WIDURI_DATABASE_PASSWORD}
    url: jdbc:mysql://localhost:3307/${WIDURI_DATABASE_NAME}
  jpa:
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.MySQLDialect

application:
  security:
    secret-key: ${JWT_SECRET_KEY:702b7afafca85bb203af3eb5d07b0c3a1ad9cee18a4ff72202b227fb989d06aea1ec1beffda5dd20360a05878f926a712a32af61a31559f20ffaf94fc58f77ba7d6d68af7f2fa8dbb0efef750b0b93b0a9e2728f3144fea133c937cb008f1710898dba68ea700e3659f67bc44514ed7f754ac882c20d8dd161de08628032a5a47180914dc9cb72b09f87b1487e415e5a620ac68b3e106befcb6eccf4361e9a29a00e39b536bb92b07f6d27eb6fbf47b5f5d8d3ab3d50d69f80511e958150aada138fa020ebd7df63c7462df31806a471005a715eb12261fbaa4cb02f3ad7d8aab6c59d707f68038cae081db9e15b261e75ca09a94cc7158486b46b06c168cff1}
    jwt-ttl: 9000000 # 150 minutes

app:
  jwt:
    refresh-token:
      expiration-ms: 600000 # 10 minutes

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    urls:
      - name: "Incoming Product API"
        url: "/IncomingProduct.yaml"
      - name: "Product API"
        url: "/product.yaml"
      - name: "User API"
        url: "/user.yaml"
    path:  /docs
    # fix path for config-url for reverse proxy, comment the 1 line bellow if u use without prefix-path
#    config-url: /projects/estock/v1/v3/api-docs/swagger-config
server:
  forward-headers-strategy: framework

logging:
  file:
    name: ${LOG_FILE_PATH:/home/yantazar/Desktop/spring/logs/widuri-estock.log}
  level:
    root: INFO
    dev.mfikri.widuriestock: DEBUG
    org:
      springframework:
        security: INFO
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%X{correlationId}] [%X{username}] - %msg%n"
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%-5level) %clr([%thread]){faint} %clr(%logger{36}){cyan} %clr([%X{correlationId}]){blue} %clr([%X{username}]){magenta} : %m%n"
---
spring:
  # ===================================================================
  # DOCKER PROFILE
  # ===================================================================
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://db:3306/${WIDURI_DATABASE_NAME}
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.MySQLDialect
logging:
  # Disable file logging and log to console (stdout) instead
  file:
    name:
  level:
    root: INFO
    dev.mfikri.widuriestock: INFO
    org:
      springframework:
        security: INFO